export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';

export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

//SHIRT
export const GET_SHIRTS_SUCESS = 'GET_SHIRTS_SUCESS';
export const GET_SHIRTS_DISCOUNT = 'GET_SHIRTS_DISCOUNT';
export const GET_SHIRTS_FILTERED = 'GET_SHIRTS_FILTERED';

//SEARCH
export const GET_SEARCH = 'GET_SEARCH';

//SINGLE PRODUCT
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
